các lệnh cấu hình trong Dockerfile
docker build -t tên docker image  .  nó sẽ được tới Dockerfile trong dự án của bạn 
docker run tên docker image : lệnh này nó sẽ sinh ra cho chúng ta 1 docker container 
docker run -it tên docker image  bash nó sẽ chạy docker container luôn 



FROM ubuntu : docker image kế thừa trên docker hub 

WORKDIR /app mặc định nó sẽ ở thư mục này trong docker container 